export const actionTypes = {
FETCH_ALL_VARIABLES_META:'FETCH_ALL_VARIABLES_META',
GOT_ALL_VARIABLES_META:'GOT_ALL_VARIABLES_META',

FETCH_SINGLE_VARIABLES_META:'FETCH_SINGLE_VARIABLES_META',
GOT_SINGLE_VARIABLES_META:'GOT_SINGLE_VARIABLES_META',

LOGIN_REQUEST: 'LOGIN_REQUEST',
LOGIN_SUCCESSFUL:'LOGIN_SUCCESSFUL',
LOGIN_ERROR: 'LOGIN_ERROR',
LOGOUT_USER:'LOGOUT_USER',
LOGOUT_SUCCESSFUL : 'LOGOUT_SUCCESSFUL',

ADD_VARIABLE:'ADD_VARIABLE',
ADD_VARIABLE_SUCCESS: 'ADD_VARIABLE_SUCCESS',
EDIT_VARIABLE_SUCCESS: 'EDIT_VARIABLE_SUCCESS',
EDIT_VARIABLE: 'EDIT_VARIABLE',
DELETE_VARIABLE_SUCCESS: 'DELETE_VARIABLE_SUCCESS',
DELETE_VARIABLE: 'DELETE_VARIABLE',
VIEW_VAIRABLES: 'VIEW_VARIABLES',
VARIABLE_REQUEST_ERROR: 'VARIABLE_REQUEST_ERROR',
}